//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoMaravillasPeru.MaravillasSOAPWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReservaHotel", Namespace="http://schemas.datacontract.org/2004/07/maravillasSOAPWS.Dominio")]
    [System.SerializableAttribute()]
    public partial class ReservaHotel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CantidadpersonasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoreservahotelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaingresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MontototalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombrehotelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumerodiasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumerohabitacionesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cantidadpersonas {
            get {
                return this.CantidadpersonasField;
            }
            set {
                if ((object.ReferenceEquals(this.CantidadpersonasField, value) != true)) {
                    this.CantidadpersonasField = value;
                    this.RaisePropertyChanged("Cantidadpersonas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigoreservahotel {
            get {
                return this.CodigoreservahotelField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoreservahotelField, value) != true)) {
                    this.CodigoreservahotelField = value;
                    this.RaisePropertyChanged("Codigoreservahotel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fechaingreso {
            get {
                return this.FechaingresoField;
            }
            set {
                if ((this.FechaingresoField.Equals(value) != true)) {
                    this.FechaingresoField = value;
                    this.RaisePropertyChanged("Fechaingreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Montototal {
            get {
                return this.MontototalField;
            }
            set {
                if ((object.ReferenceEquals(this.MontototalField, value) != true)) {
                    this.MontototalField = value;
                    this.RaisePropertyChanged("Montototal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombrehotel {
            get {
                return this.NombrehotelField;
            }
            set {
                if ((object.ReferenceEquals(this.NombrehotelField, value) != true)) {
                    this.NombrehotelField = value;
                    this.RaisePropertyChanged("Nombrehotel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numerodias {
            get {
                return this.NumerodiasField;
            }
            set {
                if ((object.ReferenceEquals(this.NumerodiasField, value) != true)) {
                    this.NumerodiasField = value;
                    this.RaisePropertyChanged("Numerodias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numerohabitaciones {
            get {
                return this.NumerohabitacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.NumerohabitacionesField, value) != true)) {
                    this.NumerohabitacionesField = value;
                    this.RaisePropertyChanged("Numerohabitaciones");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MaravillasSOAPWS.IMaravillasSOAPService")]
    public interface IMaravillasSOAPService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaravillasSOAPService/CrearReservaHotel", ReplyAction="http://tempuri.org/IMaravillasSOAPService/CrearReservaHotelResponse")]
        proyectoMaravillasPeru.MaravillasSOAPWS.ReservaHotel CrearReservaHotel(proyectoMaravillasPeru.MaravillasSOAPWS.ReservaHotel reservaHotelACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaravillasSOAPService/CrearReservaHotel", ReplyAction="http://tempuri.org/IMaravillasSOAPService/CrearReservaHotelResponse")]
        System.Threading.Tasks.Task<proyectoMaravillasPeru.MaravillasSOAPWS.ReservaHotel> CrearReservaHotelAsync(proyectoMaravillasPeru.MaravillasSOAPWS.ReservaHotel reservaHotelACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaravillasSOAPService/ObtenerReservaHotel", ReplyAction="http://tempuri.org/IMaravillasSOAPService/ObtenerReservaHotelResponse")]
        proyectoMaravillasPeru.MaravillasSOAPWS.ReservaHotel ObtenerReservaHotel(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaravillasSOAPService/ObtenerReservaHotel", ReplyAction="http://tempuri.org/IMaravillasSOAPService/ObtenerReservaHotelResponse")]
        System.Threading.Tasks.Task<proyectoMaravillasPeru.MaravillasSOAPWS.ReservaHotel> ObtenerReservaHotelAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaravillasSOAPService/ModificarReservaHotel", ReplyAction="http://tempuri.org/IMaravillasSOAPService/ModificarReservaHotelResponse")]
        proyectoMaravillasPeru.MaravillasSOAPWS.ReservaHotel ModificarReservaHotel(proyectoMaravillasPeru.MaravillasSOAPWS.ReservaHotel reservaHotelAModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaravillasSOAPService/ModificarReservaHotel", ReplyAction="http://tempuri.org/IMaravillasSOAPService/ModificarReservaHotelResponse")]
        System.Threading.Tasks.Task<proyectoMaravillasPeru.MaravillasSOAPWS.ReservaHotel> ModificarReservaHotelAsync(proyectoMaravillasPeru.MaravillasSOAPWS.ReservaHotel reservaHotelAModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaravillasSOAPService/EliminarReservaHotel", ReplyAction="http://tempuri.org/IMaravillasSOAPService/EliminarReservaHotelResponse")]
        void EliminarReservaHotel(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaravillasSOAPService/EliminarReservaHotel", ReplyAction="http://tempuri.org/IMaravillasSOAPService/EliminarReservaHotelResponse")]
        System.Threading.Tasks.Task EliminarReservaHotelAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaravillasSOAPService/ListarReservaHotel", ReplyAction="http://tempuri.org/IMaravillasSOAPService/ListarReservaHotelResponse")]
        proyectoMaravillasPeru.MaravillasSOAPWS.ReservaHotel[] ListarReservaHotel();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaravillasSOAPService/ListarReservaHotel", ReplyAction="http://tempuri.org/IMaravillasSOAPService/ListarReservaHotelResponse")]
        System.Threading.Tasks.Task<proyectoMaravillasPeru.MaravillasSOAPWS.ReservaHotel[]> ListarReservaHotelAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMaravillasSOAPServiceChannel : proyectoMaravillasPeru.MaravillasSOAPWS.IMaravillasSOAPService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MaravillasSOAPServiceClient : System.ServiceModel.ClientBase<proyectoMaravillasPeru.MaravillasSOAPWS.IMaravillasSOAPService>, proyectoMaravillasPeru.MaravillasSOAPWS.IMaravillasSOAPService {
        
        public MaravillasSOAPServiceClient() {
        }
        
        public MaravillasSOAPServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MaravillasSOAPServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaravillasSOAPServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaravillasSOAPServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public proyectoMaravillasPeru.MaravillasSOAPWS.ReservaHotel CrearReservaHotel(proyectoMaravillasPeru.MaravillasSOAPWS.ReservaHotel reservaHotelACrear) {
            return base.Channel.CrearReservaHotel(reservaHotelACrear);
        }
        
        public System.Threading.Tasks.Task<proyectoMaravillasPeru.MaravillasSOAPWS.ReservaHotel> CrearReservaHotelAsync(proyectoMaravillasPeru.MaravillasSOAPWS.ReservaHotel reservaHotelACrear) {
            return base.Channel.CrearReservaHotelAsync(reservaHotelACrear);
        }
        
        public proyectoMaravillasPeru.MaravillasSOAPWS.ReservaHotel ObtenerReservaHotel(string codigo) {
            return base.Channel.ObtenerReservaHotel(codigo);
        }
        
        public System.Threading.Tasks.Task<proyectoMaravillasPeru.MaravillasSOAPWS.ReservaHotel> ObtenerReservaHotelAsync(string codigo) {
            return base.Channel.ObtenerReservaHotelAsync(codigo);
        }
        
        public proyectoMaravillasPeru.MaravillasSOAPWS.ReservaHotel ModificarReservaHotel(proyectoMaravillasPeru.MaravillasSOAPWS.ReservaHotel reservaHotelAModificar) {
            return base.Channel.ModificarReservaHotel(reservaHotelAModificar);
        }
        
        public System.Threading.Tasks.Task<proyectoMaravillasPeru.MaravillasSOAPWS.ReservaHotel> ModificarReservaHotelAsync(proyectoMaravillasPeru.MaravillasSOAPWS.ReservaHotel reservaHotelAModificar) {
            return base.Channel.ModificarReservaHotelAsync(reservaHotelAModificar);
        }
        
        public void EliminarReservaHotel(string codigo) {
            base.Channel.EliminarReservaHotel(codigo);
        }
        
        public System.Threading.Tasks.Task EliminarReservaHotelAsync(string codigo) {
            return base.Channel.EliminarReservaHotelAsync(codigo);
        }
        
        public proyectoMaravillasPeru.MaravillasSOAPWS.ReservaHotel[] ListarReservaHotel() {
            return base.Channel.ListarReservaHotel();
        }
        
        public System.Threading.Tasks.Task<proyectoMaravillasPeru.MaravillasSOAPWS.ReservaHotel[]> ListarReservaHotelAsync() {
            return base.Channel.ListarReservaHotelAsync();
        }
    }
}
