//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace maravillasRESTWS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ciudad
    {
        public int id { get; set; }
        public string codigociudad { get; set; }
        public string descripcionciudad { get; set; }
    }
}
