//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace maravillasRESTWS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserva
    {
        public int id { get; set; }
        public string codigoreserva { get; set; }
        public string codigociudadorigen { get; set; }
        public string codigociudaddestino { get; set; }
        public string tiporeserva { get; set; }
        public System.DateTime inicioreserva { get; set; }
        public System.DateTime finreserva { get; set; }
        public string estado { get; set; }
    }
}
